-- Drafts/analyses generated by the bot on request (via Claude), kept so they
-- can be read and copied from the dashboard instead of only in Telegram.

create table if not exists drafts (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users (id) on delete cascade,
  request text not null,
  content text not null,
  created_at timestamptz not null default now()
);

alter table drafts enable row level security;

create policy "owner can manage drafts" on drafts
  for all using (owner_id = auth.uid()) with check (owner_id = auth.uid());

alter publication supabase_realtime add table drafts;
